#
# user core constraints
#
# put your clock groups in here as well as any net assignments
#

# The PLL output counters - update hierarchy for pll_imageviewer
# (ic = core_top instance name in apf_top)
#
# Only 3 PLL outputs now (general[0..2]): the former general[3] (a second,
# independently phase-shifted 99 MHz tap used to drive dram_clk directly)
# was removed. dram_clk is now generated by an ALTDDIO_OUT cell fed by
# general[2] itself (see pin_ddio_clk instance in core_top.v), so there is
# no longer a second SDRAM-domain clock to declare a group for. See
# pll_imageviewer.v and DEBUG_SUMMARY.md for why the two-PLL-tap approach
# left the SDRAM write timing unconstrained.
set_clock_groups -asynchronous \
 -group { bridge_spiclk } \
 -group { clk_74a } \
 -group { clk_74b } \
 -group { ic|mp1|altera_pll_i|general[0].gpll~PLL_OUTPUT_COUNTER|divclk } \
 -group { ic|mp1|altera_pll_i|general[1].gpll~PLL_OUTPUT_COUNTER|divclk } \
 -group { ic|mp1|altera_pll_i|general[2].gpll~PLL_OUTPUT_COUNTER|divclk }

# False paths for async FIFO Gray-code synchronizers (2FF sync is safe by design)
# The synchronizer registers are in async_fifo instances; cut timing on them.
set_false_path -to [get_registers {*|async_fifo:*|rd_gray_w1[*]}]
set_false_path -to [get_registers {*|async_fifo:*|rd_gray_w2[*]}]
set_false_path -to [get_registers {*|async_fifo:*|wr_gray_r1[*]}]
set_false_path -to [get_registers {*|async_fifo:*|wr_gray_r2[*]}]

# False paths for reset and slot synchronizers (synch_3)
set_false_path -to [get_registers {*|s_mem_rst|*}]
set_false_path -to [get_registers {*|s_vid_rst|*}]
set_false_path -to [get_registers {*|s01|*}]
set_false_path -to [get_registers {*|s_sys_rst_mem|*}]

# Multicycle paths for the SDRAM interface (matches agg23's proven design).
# mem_ctrl_inst's registers (dram_a/dram_dq/dram_dqm/commands, all clocked by
# general[2]/clk_mem) get 2 cycles of setup margin instead of 1, on the same
# clock they're already on. This is the same self-referential form agg23
# uses; it is a real constraint now that dram_clk is derived from general[2]
# via ALTDDIO_OUT (see pin_ddio_clk in core_top.v) instead of from a second,
# STA-unrelated PLL tap (the old outclk_3/general[3]).
# outclk_2 = general[2], 99MHz 0ps (controller and SDRAM chip clock source)
# See: https://github.com/agg23/openfpga-SNES/blob/master/target/pocket/core_constraints.sdc
set_multicycle_path -from {*|mem_ctrl_inst|*} -to [get_clocks {ic|mp1|altera_pll_i|general[2].gpll~PLL_OUTPUT_COUNTER|divclk}] -start -setup 2
set_multicycle_path -from {*|mem_ctrl_inst|*} -to [get_clocks {ic|mp1|altera_pll_i|general[2].gpll~PLL_OUTPUT_COUNTER|divclk}] -start -hold 1
set_multicycle_path -from [get_clocks {ic|mp1|altera_pll_i|general[2].gpll~PLL_OUTPUT_COUNTER|divclk}] -to {*|mem_ctrl_inst|*} -setup 2
set_multicycle_path -from [get_clocks {ic|mp1|altera_pll_i|general[2].gpll~PLL_OUTPUT_COUNTER|divclk}] -to {*|mem_ctrl_inst|*} -hold 1
