// pll_imageviewer.v
//
// Clock PLL for the Pocket image viewer core.
// Reference: clk_74a = 74.25 MHz from the APF framework.
//
// Outputs (VCO = 792 MHz, fractional-N):
//   outclk_0 :  39.6 MHz,   0 ps  - video pixel clock (800x720@60)
//   outclk_1 :  39.6 MHz, 6313 ps - video pixel clock, 90 deg (scaler capture)
//   outclk_2 :  99.0 MHz,   0 ps  - SDRAM controller clock (clk_mem)
//
// NOTE: 99 MHz (not 100 MHz) is required because the video needs 39.6 MHz.
// VCO=792 gives integer dividers for both: 792/20=39.6, 792/8=99.
// 100 MHz has no common VCO with 39.6 MHz in the valid range.
//
// dram_clk (the SDRAM chip clock) is NOT generated here anymore. It used to
// be a second, independently phase-shifted PLL tap (outclk_3, 180 deg), but
// that made dram_clk's real timing relationship to the address/data/command
// registers (which are clocked by outclk_2) entirely unconstrained: the two
// PLL counters are separate STA clock domains with no derived relationship,
// and core_constraints.sdc placed them in different -group blocks (mutually
// asynchronous), so Quartus never verified any skew between them. Whatever
// setup/hold margin existed on hardware was accidental to how that specific
// compile happened to place and route two unrelated PLL taps.
//
// This is fixed the way agg23's proven SDRAM controllers do it: dram_clk is
// now generated by an ALTDDIO_OUT cell (see pin_ddio_clk.v) fed by the SAME
// clock (clk_mem / outclk_2) that clocks dram_a/dram_dq/dram_dqm/commands in
// sdram_ctrl.v. Because the DDR output register and the address/data output
// registers share one clock net, Quartus can characterize their relative
// Tco with real silicon timing models instead of the skew between two
// independent PLL counters. See core_top.v for the pin_ddio_clk instance.

`timescale 1 ps / 1 ps
module pll_imageviewer (
    input  wire refclk,     // 74.25 MHz
    input  wire rst,
    output wire outclk_0,   // 39.6 MHz video
    output wire outclk_1,   // 39.6 MHz video, 90 deg
    output wire outclk_2,   // 99 MHz SDRAM controller (also drives dram_clk via DDIO)
    output wire locked
);

    altera_pll #(
        .fractional_vco_multiplier("true"),
        .reference_clock_frequency("74.25 MHz"),
        .operation_mode("normal"),
        .number_of_clocks(3),
        .output_clock_frequency0("39.6 MHz"),
        .phase_shift0("0 ps"),
        .duty_cycle0(50),
        .output_clock_frequency1("39.6 MHz"),
        .phase_shift1("6313 ps"),
        .duty_cycle1(50),
        .output_clock_frequency2("99.0 MHz"),
        .phase_shift2("0 ps"),
        .duty_cycle2(50),
        .pll_type("General"),
        .pll_subtype("General")
    ) altera_pll_i (
        .rst     (rst),
        .outclk  ({outclk_2, outclk_1, outclk_0}),
        .locked  (locked),
        .fboutclk(),
        .fbclk   (1'b0),
        .refclk  (refclk)
    );

endmodule
